import { CardDefinition } from "../types";

/** Hand-authored MVP card definitions covering core keyword families. */
export const MVP_CARD_DEFS: CardDefinition[] = [
  {
    cardNo: "MVP-001",
    name: "Strike Fairy",
    class: "neutral",
    cardType: "follower",
    cost: 1,
    attack: 1,
    defense: 1,
    traits: [],
    keywords: ["storm"],
    cardText: "Storm.",
    abilities: [],
  },
  {
    cardNo: "MVP-002",
    name: "Guardian Knight",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 1,
    defense: 3,
    traits: [],
    keywords: ["ward"],
    cardText: "Ward.",
    abilities: [],
  },
  {
    cardNo: "MVP-003",
    name: "Rush Wolf",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 2,
    defense: 1,
    traits: ["Beast"],
    keywords: ["rush"],
    cardText: "Rush.",
    abilities: [],
  },
  {
    cardNo: "MVP-004",
    name: "Bane Assassin",
    class: "neutral",
    cardType: "follower",
    cost: 3,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["bane"],
    cardText: "Bane.",
    abilities: [],
  },
  {
    cardNo: "MVP-005",
    name: "Drain Vampire",
    class: "neutral",
    cardType: "follower",
    cost: 3,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["drain"],
    cardText: "Drain.",
    abilities: [],
  },
  {
    cardNo: "MVP-006",
    name: "Fanfare Scholar",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 1,
    defense: 2,
    traits: [],
    keywords: ["fanfare"],
    cardText: "Fanfare: Draw a card.",
    abilities: [{ timing: "fanfare", effect: { op: "draw", count: 1 } }],
  },
  {
    cardNo: "MVP-007",
    name: "Last Words Mourner",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 2,
    defense: 1,
    traits: [],
    keywords: ["lastWords"],
    cardText: "Last Words: Draw a card.",
    abilities: [{ timing: "lastWords", effect: { op: "draw", count: 1 } }],
  },
  {
    cardNo: "MVP-008",
    name: "Strike Soldier",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["strike"],
    cardText: "Strike: Deal 1 damage to the enemy leader.",
    abilities: [
      {
        timing: "strike",
        effect: { op: "dealDamage", amount: 1, targets: { type: "enemyLeader" } },
      },
    ],
  },
  {
    cardNo: "MVP-009",
    name: "Fireball",
    class: "neutral",
    cardType: "spell",
    cost: 2,
    traits: [],
    keywords: [],
    cardText: "Deal 2 damage to an enemy follower.",
    abilities: [
      {
        timing: "spell",
        effect: {
          op: "dealDamage",
          amount: 2,
          targets: { type: "enemyFollower", count: 1 },
        },
      },
    ],
  },
  {
    cardNo: "MVP-010",
    name: "Healing Prayer",
    class: "haven",
    cardType: "spell",
    cost: 1,
    traits: [],
    keywords: [],
    cardText: "Give your leader +2 defense.",
    abilities: [{ timing: "spell", effect: { op: "healLeader", amount: 2 } }],
  },
  {
    cardNo: "MVP-011",
    name: "Buff Captain",
    class: "neutral",
    cardType: "follower",
    cost: 3,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["fanfare"],
    cardText: "Fanfare: Give another follower on your field +1/+1.",
    abilities: [
      {
        timing: "fanfare",
        effect: { op: "buff", atk: 1, def: 1, targets: { type: "selfFollower", count: 1 } },
      },
    ],
  },
  {
    cardNo: "MVP-012",
    name: "Vanilla Soldier",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 2,
    defense: 2,
    traits: ["Soldier"],
    keywords: [],
    cardText: "",
    abilities: [],
  },
  {
    cardNo: "MVP-013",
    name: "Eager Recruit",
    class: "neutral",
    cardType: "follower",
    cost: 1,
    attack: 1,
    defense: 1,
    traits: [],
    keywords: [],
    cardText: "",
    evolveCost: 1,
    abilities: [],
    evolvesTo: "MVP-014",
  },
  {
    cardNo: "MVP-014",
    name: "Eager Recruit Evolved",
    class: "neutral",
    cardType: "follower",
    specialType: "evolved",
    cost: 1,
    attack: 3,
    defense: 3,
    traits: [],
    keywords: ["storm", "onEvolve"],
    cardText: "Storm. On Evolve: Draw a card.",
    evolvesFrom: "MVP-013",
    abilities: [{ timing: "onEvolve", effect: { op: "draw", count: 1 } }],
  },
  {
    cardNo: "MVP-015",
    name: "Quick Ambush",
    class: "neutral",
    cardType: "spell",
    cost: 1,
    traits: [],
    keywords: ["quick"],
    cardText: "Quick. Deal 1 damage to an enemy follower.",
    abilities: [
      {
        timing: "spell",
        quick: true,
        effect: {
          op: "dealDamage",
          amount: 1,
          targets: { type: "enemyFollower", count: 1 },
        },
      },
    ],
  },
  {
    cardNo: "MVP-016",
    name: "Assail Sniper",
    class: "neutral",
    cardType: "follower",
    cost: 3,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["assail", "rush"],
    cardText: "Rush. Assail.",
    abilities: [],
  },
  {
    cardNo: "MVP-017",
    name: "Intimidate Guard",
    class: "neutral",
    cardType: "follower",
    cost: 4,
    attack: 3,
    defense: 4,
    traits: [],
    keywords: ["intimidate"],
    cardText: "Intimidate.",
    abilities: [],
  },
  {
    cardNo: "MVP-018",
    name: "Aura Mystic",
    class: "neutral",
    cardType: "follower",
    cost: 3,
    attack: 1,
    defense: 3,
    traits: [],
    keywords: ["aura"],
    cardText: "Aura.",
    abilities: [],
  },
  {
    cardNo: "MVP-019",
    name: "Board Clear",
    class: "neutral",
    cardType: "spell",
    cost: 4,
    traits: [],
    keywords: [],
    cardText: "Destroy an enemy follower.",
    abilities: [
      {
        timing: "spell",
        effect: { op: "destroy", targets: { type: "enemyFollower", count: 1 } },
      },
    ],
  },
  {
    cardNo: "MVP-020",
    name: "Goblin TOKEN",
    class: "neutral",
    cardType: "follower",
    specialType: "token",
    cost: 0,
    attack: 1,
    defense: 1,
    traits: ["Goblin"],
    keywords: [],
    cardText: "",
    abilities: [],
  },
  {
    cardNo: "MVP-021",
    name: "Token Summoner",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 1,
    defense: 2,
    traits: [],
    keywords: ["fanfare"],
    cardText: "Fanfare: Summon a Goblin token.",
    abilities: [
      {
        timing: "fanfare",
        effect: { op: "summon", tokenCardNo: "MVP-020", count: 1, zone: "field" },
      },
    ],
  },
  {
    cardNo: "MVP-022",
    name: "PP Recovery Mage",
    class: "rune",
    cardType: "follower",
    cost: 3,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["fanfare"],
    cardText: "Fanfare: Recover 1 play point.",
    abilities: [{ timing: "fanfare", effect: { op: "recoverPp", amount: 1 } }],
  },
  {
    cardNo: "MVP-023",
    name: "Overflow Dragon",
    class: "dragon",
    cardType: "follower",
    cost: 5,
    attack: 5,
    defense: 5,
    traits: [],
    keywords: ["fanfare"],
    cardText: "Fanfare: If Overflow is active, draw a card.",
    abilities: [
      {
        timing: "fanfare",
        effect: {
          op: "if",
          condition: { type: "overflow" },
          then: { op: "draw", count: 1 },
        },
      },
    ],
  },
  {
    cardNo: "MVP-024",
    name: "Combo Hunter",
    class: "forest",
    cardType: "follower",
    cost: 2,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["fanfare"],
    cardText: "Fanfare: If you've played at least 2 cards this turn, draw a card.",
    abilities: [
      {
        timing: "fanfare",
        effect: {
          op: "if",
          condition: { type: "combo", count: 2 },
          then: { op: "draw", count: 1 },
        },
      },
    ],
  },
  {
    cardNo: "MVP-025",
    name: "Super Evo Knight",
    class: "neutral",
    cardType: "follower",
    cost: 2,
    attack: 2,
    defense: 2,
    traits: [],
    keywords: ["evolve", "onSuperEvolve"],
    cardText: "Evolve. On Super-Evolve: Deal 2 damage to the enemy leader.",
    evolvesTo: "MVP-026",
    abilities: [
      {
        timing: "onSuperEvolve",
        effect: { op: "dealDamage", amount: 2, targets: { type: "enemyLeader" } },
      },
    ],
  },
  {
    cardNo: "MVP-026",
    name: "Super Evo Knight Evolved",
    class: "neutral",
    cardType: "follower",
    specialType: "evolved",
    cost: 2,
    attack: 4,
    defense: 4,
    traits: [],
    keywords: ["storm"],
    cardText: "Storm.",
    evolvesFrom: "MVP-025",
    abilities: [],
  },
];
