export const allCards = [
  "Beauty and the Beast",
  "Cosmos Fang",
  "Magical Fairy, Lilac",
  "Slade Blossoming Wolf",
  "Elf Twins' Assault",
  "Abby the Axe Girl",
  "Gerbera Bear",
  "Wood of Brambles",
  "Flower Princess",
  "Fen Sprite",
  "Tweedle Dum, Tweedle Dee",
  "Floral Breeze",
  "Woodland Band",
  "Cinderella",
  "Valiant Fencer",
  "Maisy, Red Riding Hood",
  "Amerro, Spear Knight",
  "Castle in the Sky",
  "Young Ogrehunter Momo",
  "Mach Knight",
  "Kiss of the Princess",
  "Rabbit Ear Attendant",
  "Old Man and Old Woman",
  "Bladed Hedgehog",
  "Ironwrought Defender",
  "Heroic Entry",
  "Wizardess of Oz",
  "Witch of Calamity, Millie Parfait",
  "Mystic King",
  "Falise, Leonardian Mage",
  "Milady, Mystic Queen",
  "Check",
  "Mr. Heinlein, Shadow Mage",
  "Magical Knight",
  "Gingerbread House",
  "It's a Sweets Buffet!",
  "Witch of Sweets",
  "Magical Rook",
  "Magical Bishop",
  "Blitz",
  "Witch's Cauldron",
  "The Cauldron of Calamity",
  "Jabberwock U",
  "Lævateinn Dragon",
  "Red Ragewyrm",
  "Draconir, Knuckle Dragon",
  "Tilting at Windmills",
  "Master of Draconic Arts",
  "Hammer Dragonewt",
  "Draconic Smash",
  "Elder Tortoise",
  "Trinity Dragon",
  "Dragon Summoner",
  "Lance Lizard",
  "Armor Burst",
  "Dark Alice",
  "Masquerade Ghost",
  "Odile, Black Swan",
  "Demonium, Punk Devil",
  "Baccherus, Peppy Ghostie",
  "Demon Maestro",
  "Trombone Devil",
  "Furtive Fangs",
  "Pumpkin Necromancer",
  "Parade Raven",
  "Mischievous Zombie",
  "Devilish Flautist",
  "Infernal Orchestration",
  "Princess Snow White",
  "Diamond Master",
  "Odette, White Swan",
  "Wingy Chirpy Gemstone",
  "Alice's Adventure",
  "White Knight",
  "Ruby Falcon",
  "March Hare's Teatime",
  "Tin Soldier",
  "Pinion Prince",
  "Birdkeeping Disciple",
  "Amethyst Lion",
  "Bejeweled Shrine",
  "Alice, Wonderland Explorer",
  "Angel of Chaos",
  "Rapunzel",
  "Seraph of Sin",
  "Garuel, Seraphic Leo",
  "Actress Feria",
  "Humpty Dumpty",
  "Winged Inversion",
  "Angel of Darkness",
  "Harbringer of the Night",
  "Eggsplosion",

  "Tazuna Hayakawa [Traccen Reception]",
  "Riko Kashimoto",
  "Aoi Kiryuin",
  "Silence Suzuka",
  "Smart Falcon",
  "Gold City",
  "Eat Fast! Yum Fast!",
  "Shinko Windy",
  "Eishin Flash",
  "Systematic Squats",
  "Marvelous Sunday",
  "Yukino Bijin",
  "Ines Fujin",
  "Taiki Shuttle",
  "Haru Urara",
  "Tokai Teio",
  "Narita Brian",
  "Winning Ticket",
  "Outrunning the Encroaching Heat",
  "Air Groove",
  "Hishi Amazon",
  "Trial Initiation",
  "Sirius Symboli",
  "Narita Taishin",
  "Symboli Rudolf",
  "Biko Pegasus",
  "Fuji Kiseki",
  "Agnes Tachyon",
  "Daiwa Scarlet",
  "Vodka",
  "Make! Some! NOISE!",
  "Zenno Rob Roy",
  "Agens Digital",
  "Lamplit Training of a Witch-to-Be",
  "Admire Vega",
  "Kawakami Princess",
  "Nakayama Festa",
  "Tosen Jordan",
  "Narita Top Road",
  "Special Week",
  "Oguri Cap",
  "Seiun Sky",
  "Champion's Passion",
  "King Halo",
  "Tamamo Cross",
  "Flowers for You",
  "Bamboo Memory",
  "Yaeno Muteki",
  "Grass Wonder",
  "Super Creek",
  "Hishi Akebono",
  "Maruzensky",
  "Rice Shower",
  "Nice Nature",
  "7 More Centimeters",
  "Fine Motion",
  "Mayano Top Gun",
  "My Solo Drawn to Raindrop Drums",
  "Curren Chan",
  "Twin Turbo",
  "Sakura Chiyono O",
  "Seeking the Pearl",
  "Matikanetannhauser",
  "Mejiro McQueen",
  "Gold Ship",
  "Ikuno Dictus",
  "The Will to Overtake",
  "Meisho Doto",
  "Mejiro Ryan",
  "Fate's Forecast",
  "Inari One",
  "Mejiro Dober",
  "Mejiro Ardan",
  "Mejiro Palmer",
  "T.M Opera O",
  "Riko Kashimoto [Planned Perfection]",
  "Close Knit Ambitions",
  "Take a Jab!",
  "Aoi Kiryuin [Trainers' Teamwork]",
  "Sasami Anshinzawa",
  "Tazuna Hayakawa",

  "Crystalia Tia",
  "White Wolf of Eldwood",
  "Elf Girl Liza",
  "Elf Knight Cynthia",
  "Grand Archer Seiwyn",
  "Crystalia Lily",
  "Baalt King of the Elves",
  "Elven Archery",
  "Dwarf Perfumer",
  "Elf Healer",
  "Forest Gigas",
  "Elf Bard",
  "Rose Deer",
  "Albert Levin Saber",
  "Alexander",
  "Amelia, Silver Paladin",
  "Leonidas",
  "White Paladin",
  "Jeno, Levin Vanguard",
  "Yurius, Levin Duke",
  "Whole-Souled Swing",
  "Swift Infiltrator",
  "Samurai",
  "Avant Blader",
  "Flame Soldier",
  "Gunner Maid Seria",
  "Daria Dimensional Witch",
  "Sun Oracle Pascale",
  "Anne, Belle oF Mysteria",
  "Grea the Dragonborn",
  "Rimewind",
  "Remi & Rami, Witchy Duo",
  "Shadow Witch",
  "Multipart Expirement",
  "Craig, Wizard of Mysteria",
  "Grand Gargoyle",
  "Witchbolt",
  "Magical Strategy",
  "Red-Hot Ritual",
  "Imperial Dragoon",
  "Dragonsong Flute",
  "Neptune",
  "Draconic Fervor",
  "Polyphonic Roar",
  "Siegfried",
  "Transmogrified Wyrm",
  "Dracomancer's Rites",
  "Wildfang Dragonewt",
  "Mushussu",
  "Dragontamer",
  "Twin-Headed Dragon",
  "Draconic Armor",
  "Vania, Vampire Princess",
  "Soul Dealer",
  "Underworld Watchman Khawy",
  "Azazel",
  "Vampiric Fortress",
  "Veight, Vampire Noble",
  "Trick Dullahan",
  "Precious Bloodfangs",
  "Mini Soul Devil",
  "Moriana the Bejeweled",
  "Demonic Hedonist",
  "Bone Chimera",
  "Necrocarnival",
  "Heavenly Aegis",
  "Enstatued Seraph",
  "Kaguya",
  "Tribunal of Good and Evil",
  "Elana's Prayer",
  "Radiance Angel",
  "Saphire Priestess",
  "Beastcall Aria",
  "Frog Cleric",
  "Sky Sprite",
  "Soul Collector",
  "Sledgehammer Exorcist",
  "Emerald Maiden",
  "Dark Angel Olivia",
  "Bahamut",
  "Demonic Simulacrum",
  "Archangel Reina",
  "Surefire Bullet",
  "Unicorn Dancer Unicorn",
  "Gourmet Emperor Khaiza",
  "Call of Cocytus",
  "Hamsa",
  "Sektor",
  "Dance of Death",

  "Skullfane",
  "Hare of Illusions",
  "Priest of the Cudgel",
  "Acolyte's Light",
  "Dual Flames",
  "Ardent Nun",
  "Guardian Nun",
  "Pinion Prayer",
  "Beastly Vow",
  "Queen Vampire",
  "Alucard",
  "Playful Necomancer",
  "Midnight Vampire",
  "Night Horde",
  "Lesser Mummy",
  "Lilith",
  "Undying Resentment",
  "Summon Bloodkin",
  "Fafnir",
  "Dragon Oracle",
  "Dragon Warrior",
  "Dragonewt Princess",
  "Dragonguard",
  "Roc",
  "Glint Dragon",
  "Dragonrider",
  "Seabrand Dragon",
  "Mythril Golem",
  "Rune Blade Summoner",
  "Demonflame Mage",
  "Insight",
  "Fire Chain",
  "Penguin Wizard",
  "Sammy Wizard's Apprentice",
  "Magic Missle",
  "Conjure Golem",
  "Tsubasa",
  "Latham, Vanguard Captain",
  "Floral Fencer",
  "Moonlight Assassin",
  "White General",
  "Fencer",
  "Oathless Knight",
  "Quickblader",
  "Unbridled Fury",
  "Aria, Fairy Princess",
  "Titania's Sanctuary",
  "Rose Gardener",
  "Waltzing Fairy",
  "Fairy Caster",
  "Treant",
  "Water Fairy",
  "Elf Wanderer",
  "Sylvan Justice",
  "Rose Queen",
  "Ancient Elf",
  "Rhinoceroach",
  "Robin Hood",
  "Silver Bolt",
  "Homecoming",
  "Elven Princess Mage",
  "Blessed Fairy Dancer",
  "Elf Child May",
  "Fairy Beast",
  "Noble Fairy",
  "Nature's Guidance",
  "Harvest Festival",
  "Elf Metallurgist",
  "Archer",
  "Fairy Whisperer",
  "Okami",
  "Mana Elk",
  "Fairy Circle",
  "Woodkin Curse",
  "Woodland Refuge",
  "Sea Queen Otohime",
  "Aurelia, Regal Saber",
  "Shadowed Assassin",
  "Frontguard General",
  "Alwida's Command",
  "Royal Banner",
  "Maid Leader",
  "Gemstaff Commander",
  "Sage Commander",
  "Swordsman",
  "Pompous Princess",
  "Ninja Master",
  "Arthurian Light",
  "Ninja Trainee",
  "Fervid Soldier",
  "Luminous Knight",
  "Veteran Lancer",
  "Navy Lieutenant",
  "Novice Trooper",
  "Forge Weaponry",
  "Onslaught",
  "Arch Summoner Erasmus",
  "Merlin",
  "Ancient Alchemist",
  "Arcane Enlightenment",
  "Dimension Shift",
  "Juno's Secret Laboratory",
  "Spectral Wizard",
  "Flame Destroyer",
  "Dragonbond Mage",
  "Golem Protection",
  "Alchemical Lore",
  "Fate's Hand",
  "Price of Magic",
  "Runic Guardian",
  "Crafty Warlock",
  "Lightning Shooter",
  "Wind Blast",
  "Sorcery Cache",
  "Fiery Embrace",
  "Alchemist's Workshop",
  "Teachings of Creation",
  "Dark Dragoon Forte",
  "Zirnitra",
  "Aiela, Dragon Knight",
  "Genesis Dragon",
  "Shapeshifting Mage",
  "Phoenix Roost",
  "Wyvern Cavalier",
  "Dragonewt Scholar",
  "Shenlong",
  "Imprisoned Dragon",
  "Conflagration",
  "Serpent's Wrath",
  "Wyrm Spire",
  "Ivory Dragon",
  "Fire Lizard",
  "Ace Dragoon",
  "Mist Dragon",
  "Dread Dragon",
  "Blazing Breath",
  "Dragon Wings",
  "Dragon Emissary",
  "Cerberus",
  "Lord Atomy",
  "Medusa",
  "Righteous Devil",
  "Mordecai the Duelist",
  "Dire Bond",
  "Hell's Unleasher",
  "Crazed Executioner",
  "Dark Summoner",
  "Dark General",
  "Phantom Howl",
  "Death's Breath",
  "Soul Conversion",
  "Skeleton Fighter",
  "Ambling Wraith",
  "Spectre",
  "Spartoi Sergeant",
  "Rabbit Necromancer",
  "Wardrobe Raider",
  "Undead King",
  "Razory Claw",
  "Moon Al-mi'raj",
  "Jeanne d'Arc",
  "Arch Priestess Laelia",
  "Themis's Decree",
  "Chorus of Prayer",
  "Sacred Plea",
  "Temple Defender",
  "Prism Priestess",
  "Cleric Lancer",
  "Shrine Knight Maiden",
  "Blackened Scripture",
  "Dark Offering",
  "Holy Sentinel",
  "Cruel Priestess",
  "Sister Initiate",
  "Mainyu",
  "Snake Priestess",
  "Curate",
  "Hallowed Dogma",
  "Guardian Sun",
  "Death Sentence",
  "Gabriel",
  "Lucifer",
  "Flame and Glass",
  "Urd",
  "Wind God",
  "Gilgamesh",
  "Bellringer Angel",
  "Altered Fate",
  "Path to Purgatory",
  "Lizardman",
  "Goblinmount Demon",
  "Harnessed Flame",
  "Harnessed Glass",
  "Demonic Strike",
  "Execution",
  "Trail of Light",
  "Goblin",
  "Fighter",
  "Goliath",
  "Angelic Sword Maiden",
  "Healing Angel",
  "Angelic Snipe",
  "Angelic Barrage",
];
