export const allCards = [
  "Bellringer Angel",
  "Blazing Breath",
  "Dragon Oracle",
  "Surefire Bullet",
  "Aiela, Dragon Knight",
  "Dragon Warrior",
  "Serpent's Wrath",
  "Path to Purgatory",
  "Execution",
  "Dark Dragoon Forte",
  "Shenlong",
  "Dark Angel Olivia",
  "Conflagration",
  "Oguri Cap",
  "Riko Kashimoto [Planned Perfection]",
  "Bahamut",
  "Hishi Akebono",
];
