export const allCardsEvo = [
  "Cosmos Fang Evolved",
  "Slade Blossoming Wolf Evolved",
  "Gerbera Bear Evolved",
  "Tweedle Dum, Tweedle Dee Evolved",
  "Valiant Fencer Evolved",
  "Amerro, Spear Knight Evolved",
  "Mach Knight Evolved",
  "Bladed Hedgehog Evolved",
  "Mystic King Evolved",
  "Milady, Mystic Queen Evolved",
  "Magical Knight Evolved",
  "Witch of Sweets Evolved",
  "Lævateinn Dragon Evolved",
  "Lævateinn Dragon Attack Form Evolved",
  "Draconir, Knuckle Dragon Evolved",
  "Hammer Dragonewt Evolved",
  "Dragon Summoner Evolved",
  "Masquerade Ghost Evolved",
  "Baccherus, Peppy Ghostie Evolved",
  "Trombone Devil Evolved",
  "Mischievous Zombie Evolved",
  "Diamond Master Evolved",
  "Wingy Chirpy Gemstone Evolved",
  "Ruby Falcon Evolved",
  "Pinion Prince Evolved",
  "Alice, Wonderland Explorer Evolved",
  "Garuel, Seraphic Leo Evolved",
  "Humpty Dumpty Evolved",
  "Harbringer of the Night Evolved",

  "Silence Suzuka Evolved",
  "Tokai Teio Evolved",
  "Agnes Tachyon Evolved",
  "Special Week Evolved",
  "Maruzensky Evolved",
  "Mejiro McQueen Evolved",
  "Carrot",

  "Crystalia Tia Evolved",
  "Grand Archer Seiwyn Evolved",
  "Crystalia Lily Evolved",
  "Forest Gigas Evolved",
  "Albert Levin Saber Evolved",
  "Leonidas Evolved",
  "Jeno, Levin Vanguard Evolved",
  "Avant Blader Evolved",
  "Daria Dimensional Witch Evolved",
  "Anne, Belle oF Mysteria Evolved",
  "Remi & Rami, Witchy Duo Evolved",
  "Craig, Wizard of Mysteria Evolved",
  "Imperial Dragoon Evolved",
  "Neptune Evolved",
  "Siegfried Evolved",
  "Dragontamer Evolved",
  "Soul Dealer Evolved",
  "Azazel Evolved",
  "Veight, Vampire Noble Evolved",
  "Demonic Hedonist Evolved",
  "Heavenly Aegis Evolved",
  "Kaguya Evolved",
  "Radiance Angel Evolved",
  "Soul Collector Evolved",
  "Bahamut Evolved",
  "Archangel Reina Evolved",
  "Unicorn Dancer Unicorn Evolved",
  "Sektor Evolved",

  "Priest of the Cudgel Evolved",
  "Ardent Nun Evolved",
  "Guardian Nun Evolved",
  "Playful Necomancer Evolved",
  "Lesser Mummy Evolved",
  "Lilith Evolved",
  "Dragon Warrior Evolved",
  "Roc Evolved",
  "Dragonrider Evolved",
  "Demonflame Mage Evolved",
  "Penguin Wizard Evolved",
  "Sammy Wizard's Apprentice Evolved",
  "Floral Fencer Evolved",
  "Oathless Knight Evolved",
  "Quickblader Evolved",
  "Rose Gardener Evolved",
  "Treant Evolved",
  "Water Fairy Evolved",
  "Ancient Elf Evolved",
  "Rhinoceroach Evolved",
  "Elven Princess Mage Evolved",
  "Archer Evolved",
  "Sea Queen Otohime Evolved",
  "Shadowed Assassin Evolved",
  "Maid Leader Evolved",
  "Fervid Soldier Evolved",
  "Merlin Evolved",
  "Ancient Alchemist Evolved",
  "Spectral Wizard Evolved",
  "Crafty Warlock Evolved",
  "Dark Dragoon Forte Evolved U",
  "Shapeshifting Mage Evolved",
  "Shenlong Evolved",
  "Ivory Dragon Evolved",
  "Cerberus Evolved",
  "Righteous Devil Evolved",
  "Crazed Executioner Evolved",
  "Wardrobe Raider Evolved",
  "Jeanne d'Arc Evolved",
  "Arch Priestess Laelia Evolved",
  "Prism Priestess Evolved",
  "Mainyu Evolved",
  "Lucifer Evolved",
  "Urd Evolved",
  "Bellringer Angel Evolved",
  "Goblinmount Demon Evolved",
  "Goblin Evolved",
  "Goliath Evolved",
  "Healing Angel Evolved",
];
