export const allCardsEvo = [
  "Deepwood Anomaly Evolved",
  "King Elephant Evolved",
  "Sukuna, Brave and Small Evolved",
  "Fita the Gentle Elf Evolved",
  "Mars, Silent Flame General Evolved",
  "Barbarossa Evolved",
  "Shrouded Assassin Evolved",
  "Tristan of the Round Table Evolved",
  "Wordwielder Ginger Evolved",
  "Europa Evolved",
  "Magic Illusionist Evolved",
  "Dazzling Healer Evolved",
  "Python Evolved",
  "Lævateinn Dragon, Defense Form Evolved",
  "Lævateinn Dragon, Blast Form Evolved",
  "Star Phoenix Evolved",
  "Cetus Evolved",
  "Hippocampus Evolved",
  "Howling Demon Evolved",
  "Stheno Evolved",
  "Fenrir Evolved",
  "Frogbat Evolved",
  "Dark Jeanne Evolved",
  "Zoe, Princess of Goldenia Evolved",
  "Star Priestess Evolved",
  "Israfil Evolved",
  "Grimnir, War Cyclone Evolved",
  "Goblin Princess Evolved",
  "Owlcat Evolved",

  "Cosmos Fang Evolved",
  "Slade Blossoming Wolf Evolved",
  "Gerbera Bear Evolved",
  "Tweedle Dum, Tweedle Dee Evolved",
  "Valiant Fencer Evolved",
  "Amerro, Spear Knight Evolved",
  "Mach Knight Evolved",
  "Bladed Hedgehog Evolved",
  "Mystic King Evolved",
  "Milady, Mystic Queen Evolved",
  "Magical Knight Evolved",
  "Witch of Sweets Evolved",
  "Lævateinn Dragon Evolved",
  "Lævateinn Dragon Attack Form Evolved",
  "Draconir, Knuckle Dragon Evolved",
  "Hammer Dragonewt Evolved",
  "Dragon Summoner Evolved",
  "Masquerade Ghost Evolved",
  "Baccherus, Peppy Ghostie Evolved",
  "Trombone Devil Evolved",
  "Mischievous Zombie Evolved",
  "Diamond Master Evolved",
  "Wingy Chirpy Gemstone Evolved",
  "Ruby Falcon Evolved",
  "Pinion Prince Evolved",
  "Alice, Wonderland Explorer Evolved",
  "Garuel, Seraphic Leo Evolved",
  "Humpty Dumpty Evolved",
  "Harbringer of the Night Evolved",

  "Silence Suzuka Evolved",
  "Tokai Teio Evolved",
  "Agnes Tachyon Evolved",
  "Special Week Evolved",
  "Maruzensky Evolved",
  "Mejiro McQueen Evolved",
  "Carrot",

  "Crystalia Tia Evolved",
  "Grand Archer Seiwyn Evolved",
  "Crystalia Lily Evolved",
  "Forest Gigas Evolved",
  "Albert Levin Saber Evolved",
  "Leonidas Evolved",
  "Jeno, Levin Vanguard Evolved",
  "Avant Blader Evolved",
  "Daria Dimensional Witch Evolved",
  "Anne, Belle oF Mysteria Evolved",
  "Remi & Rami, Witchy Duo Evolved",
  "Craig, Wizard of Mysteria Evolved",
  "Imperial Dragoon Evolved",
  "Neptune Evolved",
  "Siegfried Evolved",
  "Dragontamer Evolved",
  "Soul Dealer Evolved",
  "Azazel Evolved",
  "Veight, Vampire Noble Evolved",
  "Demonic Hedonist Evolved",
  "Heavenly Aegis Evolved",
  "Kaguya Evolved",
  "Radiance Angel Evolved",
  "Soul Collector Evolved",
  "Bahamut Evolved",
  "Archangel Reina Evolved",
  "Unicorn Dancer Unicorn Evolved",
  "Sektor Evolved",

  "Priest of the Cudgel Evolved",
  "Ardent Nun Evolved",
  "Guardian Nun Evolved",
  "Playful Necomancer Evolved",
  "Lesser Mummy Evolved",
  "Lilith Evolved",
  "Dragon Warrior Evolved",
  "Roc Evolved",
  "Dragonrider Evolved",
  "Demonflame Mage Evolved",
  "Penguin Wizard Evolved",
  "Sammy Wizard's Apprentice Evolved",
  "Floral Fencer Evolved",
  "Oathless Knight Evolved",
  "Quickblader Evolved",
  "Rose Gardener Evolved",
  "Treant Evolved",
  "Water Fairy Evolved",
  "Ancient Elf Evolved",
  "Rhinoceroach Evolved",
  "Elven Princess Mage Evolved",
  "Archer Evolved",
  "Sea Queen Otohime Evolved",
  "Shadowed Assassin Evolved",
  "Maid Leader Evolved",
  "Fervid Soldier Evolved",
  "Merlin Evolved",
  "Ancient Alchemist Evolved",
  "Spectral Wizard Evolved",
  "Crafty Warlock Evolved",
  "Dark Dragoon Forte Evolved U",
  "Shapeshifting Mage Evolved",
  "Shenlong Evolved",
  "Ivory Dragon Evolved",
  "Cerberus Evolved",
  "Righteous Devil Evolved",
  "Crazed Executioner Evolved",
  "Wardrobe Raider Evolved",
  "Jeanne d'Arc Evolved",
  "Arch Priestess Laelia Evolved",
  "Prism Priestess Evolved",
  "Mainyu Evolved",
  "Lucifer Evolved",
  "Urd Evolved",
  "Bellringer Angel Evolved",
  "Goblinmount Demon Evolved",
  "Goblin Evolved",
  "Goliath Evolved",
  "Healing Angel Evolved",
];

export const set3Evo = [
  "Cosmos Fang Evolved",
  "Slade Blossoming Wolf Evolved",
  "Gerbera Bear Evolved",
  "Tweedle Dum, Tweedle Dee Evolved",
  "Valiant Fencer Evolved",
  "Amerro, Spear Knight Evolved",
  "Mach Knight Evolved",
  "Bladed Hedgehog Evolved",
  "Mystic King Evolved",
  "Milady, Mystic Queen Evolved",
  "Magical Knight Evolved",
  "Witch of Sweets Evolved",
  "Lævateinn Dragon Evolved",
  "Lævateinn Dragon Attack Form Evolved",
  "Draconir, Knuckle Dragon Evolved",
  "Hammer Dragonewt Evolved",
  "Dragon Summoner Evolved",
  "Masquerade Ghost Evolved",
  "Baccherus, Peppy Ghostie Evolved",
  "Trombone Devil Evolved",
  "Mischievous Zombie Evolved",
  "Diamond Master Evolved",
  "Wingy Chirpy Gemstone Evolved",
  "Ruby Falcon Evolved",
  "Pinion Prince Evolved",
  "Alice, Wonderland Explorer Evolved",
  "Garuel, Seraphic Leo Evolved",
  "Humpty Dumpty Evolved",
  "Harbringer of the Night Evolved",
];

export const setUMAEvo = [
  "Silence Suzuka Evolved",
  "Tokai Teio Evolved",
  "Agnes Tachyon Evolved",
  "Special Week Evolved",
  "Maruzensky Evolved",
  "Mejiro McQueen Evolved",
  "Carrot",
];

export const set2Evo = [
  "Crystalia Tia Evolved",
  "Grand Archer Seiwyn Evolved",
  "Crystalia Lily Evolved",
  "Forest Gigas Evolved",
  "Albert Levin Saber Evolved",
  "Leonidas Evolved",
  "Jeno, Levin Vanguard Evolved",
  "Avant Blader Evolved",
  "Daria Dimensional Witch Evolved",
  "Anne, Belle oF Mysteria Evolved",
  "Remi & Rami, Witchy Duo Evolved",
  "Craig, Wizard of Mysteria Evolved",
  "Imperial Dragoon Evolved",
  "Neptune Evolved",
  "Siegfried Evolved",
  "Dragontamer Evolved",
  "Soul Dealer Evolved",
  "Azazel Evolved",
  "Veight, Vampire Noble Evolved",
  "Demonic Hedonist Evolved",
  "Heavenly Aegis Evolved",
  "Kaguya Evolved",
  "Radiance Angel Evolved",
  "Soul Collector Evolved",
  "Bahamut Evolved",
  "Archangel Reina Evolved",
  "Unicorn Dancer Unicorn Evolved",
  "Sektor Evolved",
];

export const set1Evo = [
  "Priest of the Cudgel Evolved",
  "Ardent Nun Evolved",
  "Guardian Nun Evolved",
  "Playful Necomancer Evolved",
  "Lesser Mummy Evolved",
  "Lilith Evolved",
  "Dragon Warrior Evolved",
  "Roc Evolved",
  "Dragonrider Evolved",
  "Demonflame Mage Evolved",
  "Penguin Wizard Evolved",
  "Sammy Wizard's Apprentice Evolved",
  "Floral Fencer Evolved",
  "Oathless Knight Evolved",
  "Quickblader Evolved",
  "Rose Gardener Evolved",
  "Treant Evolved",
  "Water Fairy Evolved",
  "Ancient Elf Evolved",
  "Rhinoceroach Evolved",
  "Elven Princess Mage Evolved",
  "Archer Evolved",
  "Sea Queen Otohime Evolved",
  "Shadowed Assassin Evolved",
  "Maid Leader Evolved",
  "Fervid Soldier Evolved",
  "Merlin Evolved",
  "Ancient Alchemist Evolved",
  "Spectral Wizard Evolved",
  "Crafty Warlock Evolved",
  "Dark Dragoon Forte Evolved U",
  "Shapeshifting Mage Evolved",
  "Shenlong Evolved",
  "Ivory Dragon Evolved",
  "Cerberus Evolved",
  "Righteous Devil Evolved",
  "Crazed Executioner Evolved",
  "Wardrobe Raider Evolved",
  "Jeanne d'Arc Evolved",
  "Arch Priestess Laelia Evolved",
  "Prism Priestess Evolved",
  "Mainyu Evolved",
  "Lucifer Evolved",
  "Urd Evolved",
  "Bellringer Angel Evolved",
  "Goblinmount Demon Evolved",
  "Goblin Evolved",
  "Goliath Evolved",
  "Healing Angel Evolved",
];

export const forestEvo = [
  "Deepwood Anomaly Evolved",
  "King Elephant Evolved",
  "Sukuna, Brave and Small Evolved",
  "Fita the Gentle Elf Evolved",
  "Cosmos Fang Evolved",
  "Slade Blossoming Wolf Evolved",
  "Gerbera Bear Evolved",
  "Tweedle Dum, Tweedle Dee Evolved",
  "Silence Suzuka Evolved",
  "Crystalia Tia Evolved",
  "Grand Archer Seiwyn Evolved",
  "Crystalia Lily Evolved",
  "Forest Gigas Evolved",
  "Rose Gardener Evolved",
  "Treant Evolved",
  "Water Fairy Evolved",
  "Ancient Elf Evolved",
  "Rhinoceroach Evolved",
  "Elven Princess Mage Evolved",
  "Archer Evolved",
];

export const swordEvo = [
  "Mars, Silent Flame General Evolved",
  "Barbarossa Evolved",
  "Shrouded Assassin Evolved",
  "Tristan of the Round Table Evolved",
  "Valiant Fencer Evolved",
  "Amerro, Spear Knight Evolved",
  "Mach Knight Evolved",
  "Bladed Hedgehog Evolved",
  "Tokai Teio Evolved",
  "Albert Levin Saber Evolved",
  "Leonidas Evolved",
  "Jeno, Levin Vanguard Evolved",
  "Avant Blader Evolved",
  "Floral Fencer Evolved",
  "Oathless Knight Evolved",
  "Quickblader Evolved",
  "Sea Queen Otohime Evolved",
  "Shadowed Assassin Evolved",
  "Maid Leader Evolved",
  "Fervid Soldier Evolved",
];

export const runeEvo = [
  "Wordwielder Ginger Evolved",
  "Europa Evolved",
  "Magic Illusionist Evolved",
  "Dazzling Healer Evolved",
  "Mystic King Evolved",
  "Milady, Mystic Queen Evolved",
  "Magical Knight Evolved",
  "Witch of Sweets Evolved",
  "Agnes Tachyon Evolved",
  "Daria Dimensional Witch Evolved",
  "Anne, Belle oF Mysteria Evolved",
  "Remi & Rami, Witchy Duo Evolved",
  "Craig, Wizard of Mysteria Evolved",
  "Demonflame Mage Evolved",
  "Penguin Wizard Evolved",
  "Sammy Wizard's Apprentice Evolved",
  "Merlin Evolved",
  "Ancient Alchemist Evolved",
  "Spectral Wizard Evolved",
  "Crafty Warlock Evolved",
];

export const dragonEvo = [
  "Python Evolved",
  "Lævateinn Dragon, Defense Form Evolved",
  "Lævateinn Dragon, Blast Form Evolved",
  "Star Phoenix Evolved",
  "Cetus Evolved",
  "Hippocampus Evolved",
  "Lævateinn Dragon Evolved",
  "Lævateinn Dragon Attack Form Evolved",
  "Draconir, Knuckle Dragon Evolved",
  "Hammer Dragonewt Evolved",
  "Dragon Summoner Evolved",
  "Special Week Evolved",
  "Imperial Dragoon Evolved",
  "Neptune Evolved",
  "Siegfried Evolved",
  "Dragontamer Evolved",
  "Dragon Warrior Evolved",
  "Roc Evolved",
  "Dragonrider Evolved",
  "Dark Dragoon Forte Evolved U",
  "Shapeshifting Mage Evolved",
  "Shenlong Evolved",
  "Ivory Dragon Evolved",
];

export const abyssEvo = [
  "Howling Demon Evolved",
  "Stheno Evolved",
  "Fenrir Evolved",
  "Frogbat Evolved",
  "Masquerade Ghost Evolved",
  "Baccherus, Peppy Ghostie Evolved",
  "Trombone Devil Evolved",
  "Mischievous Zombie Evolved",
  "Maruzensky Evolved",
  "Soul Dealer Evolved",
  "Azazel Evolved",
  "Veight, Vampire Noble Evolved",
  "Demonic Hedonist Evolved",
  "Playful Necomancer Evolved",
  "Lesser Mummy Evolved",
  "Lilith Evolved",
  "Cerberus Evolved",
  "Righteous Devil Evolved",
  "Crazed Executioner Evolved",
  "Wardrobe Raider Evolved",
];

export const havenEvo = [
  "Dark Jeanne Evolved",
  "Zoe, Princess of Goldenia Evolved",
  "Star Priestess Evolved",
  "Diamond Master Evolved",
  "Wingy Chirpy Gemstone Evolved",
  "Ruby Falcon Evolved",
  "Pinion Prince Evolved",
  "Mejiro McQueen Evolved",
  "Heavenly Aegis Evolved",
  "Kaguya Evolved",
  "Radiance Angel Evolved",
  "Soul Collector Evolved",
  "Priest of the Cudgel Evolved",
  "Ardent Nun Evolved",
  "Guardian Nun Evolved",
  "Jeanne d'Arc Evolved",
  "Arch Priestess Laelia Evolved",
  "Prism Priestess Evolved",
  "Mainyu Evolved",
];

export const neutralEvo = [
  "Israfil Evolved",
  "Grimnir, War Cyclone Evolved",
  "Goblin Princess Evolved",
  "Owlcat Evolved",
  "Alice, Wonderland Explorer Evolved",
  "Garuel, Seraphic Leo Evolved",
  "Humpty Dumpty Evolved",
  "Harbringer of the Night Evolved",
  "Carrot",
  "Bahamut Evolved",
  "Archangel Reina Evolved",
  "Unicorn Dancer Unicorn Evolved",
  "Sektor Evolved",
  "Lucifer Evolved",
  "Urd Evolved",
  "Bellringer Angel Evolved",
  "Goblinmount Demon Evolved",
  "Goblin Evolved",
  "Goliath Evolved",
  "Healing Angel Evolved",
];
