export const allTokens = [
  "bp15-pr19 TOKEN",
  "bp15-pr20 TOKEN",
  "bp15-t01 TOKEN",
  "bp15-t02 TOKEN",
  "bp15-t03 TOKEN",
  "bp15-pr21 TOKEN",
  "bp15-pr22 TOKEN",
  "bp15-pr23 TOKEN",
  "bp15-pr24 TOKEN",
  "bp15-pr25 TOKEN",
  "bp15-t04 TOKEN",
  "bp15-pr26 TOKEN",
  "bp15-pr27 TOKEN",
  "bp15-pr28 TOKEN",

  "bp14-t01 TOKEN",
  "bp14-t02 TOKEN",
  "bp14-t03 TOKEN",
  "bp14-t04 TOKEN",
  "bp14-t05 TOKEN",
  "bp14-t06 TOKEN",
  "bp14-t07 TOKEN",

  "Anne's Summoning TOKEN",
  "Resentful Blaze TOKEN",
  "Blood Arts TOKEN",
  "Darkest Desire TOKEN",
  "Keenedge Artifact TOKEN",

  "Carbuncle's Sparkle TOKEN",
  "Twilight Blade TOKEN",
  "Armored Tentacle TOKEN",
  "Assault Tentacle TOKEN",
  "Medusiana TOKEN",

  "Val, Trusty Getaway Car TOKEN",
  "Magitrain TOKEN",
  "Dutiful Steed TOKEN",
  "Bullet Bike TOKEN",
  "Arcane Personnel Carrier TOKEN",

  "Exterminus Weapon TOKEN",
  "Devoted Dragon TOKEN",

  "Instant Poison TOKEN",
  "Eternal Potion TOKEN",
  "Mysterian Missile TOKEN",
  "Aftershock TOKEN",

  "Lloyd TOKEN",
  "Victoria TOKEN",
  "Otohime's Vanguard TOKEN",

  "Assembly Droid TOKEN",
  "Repair Mode TOKEN",
  "Naterran Great Tree TOKEN",

  "Cute Earrings TOKEN",
  "Cool Earrings TOKEN",
  "Passion Earrings TOKEN",
  "Celestial Shikigami TOKEN",
  "Paper Shikigami TOKEN",
  "One-Tailed Fox TOKEN",
  "Destruction in White TOKEN",
  "Destruction in Black TOKEN",
  "Puppet TOKEN",
  "Ancient Artifact TOKEN",
  "Mystic Artifact TOKEN",
  "Serpent TOKEN",
  "Goblin King TOKEN",
  "Gargantuan Ghost TOKEN",
  "Crystalia Eve TOKEN",
  "Shield Guardian TOKEN",
  "Leonidas's Resolve TOKEN",
  "Magical Pawn TOKEN",
  "Megalorca TOKEN",
  "Hellflame Dragon TOKEN",
  "Draconic Weapon TOKEN",
  "Ephemeral Moon TOKEN",
  "Thorn Burst TOKEN",
  "Fairy Wisp TOKEN",
  "Fairy TOKEN",
  "Otohime's Bodyguard TOKEN",
  "Knight TOKEN",
  "Viking TOKEN",
  "Steelclad Knight TOKEN",
  "Strikeform Golem TOKEN",
  "Guardform Golem TOKEN",
  "Magic Sediment TOKEN",
  "Dragon TOKEN",
  "Mimi TOKEN",
  "Coco TOKEN",
  "Ghost TOKEN",
  "Forest Bat TOKEN",
  "Holy Falcon TOKEN",
  "Holy Tiger TOKEN",
];
