export const allTokens = [
  "Annihilating Onslaught TOKEN",
  "Remnant of Hollowness TOKEN",
  "Gilded Blade TOKEN",
  "Gilded Goblet TOKEN",
  "Gilded Boots TOKEN",
  "Ersatz Elimination TOKEN",
  "Melodious Monody TOKEN",
  "Fangs of Ardent Destruction TOKEN",
  "Wings of Desire TOKEN",
  "Scream Diffusion TOKEN",
  "Rulenye, Screaming Echo TOKEN",
  "Torrent of Despair TOKEN",
  "Great Testimony TOKEN",
  "Ravenous Sweetness TOKEN",

  "Sootspawn TOKEN",
  "Glittering Gold TOKEN",
  "Flame General's Regalia TOKEN",
  "Tidal Tyranny TOKEN",
  "Wolfling's Struggle TOKEN",
  "Fox of Invitation TOKEN",
  "Mercurial Might TOKEN",

  "Anne's Summoning TOKEN",
  "Resentful Blaze TOKEN",
  "Blood Arts TOKEN",
  "Darkest Desire TOKEN",
  "Keenedge Artifact TOKEN",

  "Carbuncle's Sparkle TOKEN",
  "Twilight Blade TOKEN",
  "Armored Tentacle TOKEN",
  "Assault Tentacle TOKEN",
  "Medusiana TOKEN",

  "Val, Trusty Getaway Car TOKEN",
  "Magitrain TOKEN",
  "Dutiful Steed TOKEN",
  "Bullet Bike TOKEN",
  "Arcane Personnel Carrier TOKEN",

  "Exterminus Weapon TOKEN",
  "Devoted Dragon TOKEN",

  "Instant Poison TOKEN",
  "Eternal Potion TOKEN",
  "Mysterian Missile TOKEN",
  "Aftershock TOKEN",

  "Lloyd TOKEN",
  "Victoria TOKEN",
  "Otohime's Vanguard TOKEN",

  "Assembly Droid TOKEN",
  "Repair Mode TOKEN",
  "Naterran Great Tree TOKEN",

  "Cute Earrings TOKEN",
  "Cool Earrings TOKEN",
  "Passion Earrings TOKEN",
  "Celestial Shikigami TOKEN",
  "Paper Shikigami TOKEN",
  "One-Tailed Fox TOKEN",
  "Destruction in White TOKEN",
  "Destruction in Black TOKEN",
  "Puppet TOKEN",
  "Ancient Artifact TOKEN",
  "Mystic Artifact TOKEN",
  "Serpent TOKEN",
  "Goblin King TOKEN",
  "Gargantuan Ghost TOKEN",
  "Crystalia Eve TOKEN",
  "Shield Guardian TOKEN",
  "Leonidas's Resolve TOKEN",
  "Magical Pawn TOKEN",
  "Megalorca TOKEN",
  "Hellflame Dragon TOKEN",
  "Draconic Weapon TOKEN",
  "Ephemeral Moon TOKEN",
  "Thorn Burst TOKEN",
  "Fairy Wisp TOKEN",
  "Fairy TOKEN",
  "Otohime's Bodyguard TOKEN",
  "Knight TOKEN",
  "Viking TOKEN",
  "Steelclad Knight TOKEN",
  "Strikeform Golem TOKEN",
  "Guardform Golem TOKEN",
  "Magic Sediment TOKEN",
  "Dragon TOKEN",
  "Mimi TOKEN",
  "Coco TOKEN",
  "Ghost TOKEN",
  "Forest Bat TOKEN",
  "Holy Falcon TOKEN",
  "Holy Tiger TOKEN",
];
