// Runtime card-metadata lookup + filtering helpers for the deck builder.
//
// cardData.json is generated by src/scripts/buildcarddata.cjs (merged from the
// scraper output) and is keyed by card NAME -> details. See that script.

import cardData from "./cardData.json";

export const getDetails = (name) => cardData[name] || null;

// Collab "classes" aren't stored in the `class` field — those cards carry a base
// craft (often neutral) — but they're identifiable by trait. Detect them so a
// collab deck is labelled by its collab rather than its base craft.
const collabClass = (name) => {
  const t = (cardData[name] && cardData[name].trait) || "";
  if (/Vanguard/i.test(t)) return "vanguard";
  if (/iM@S/i.test(t)) return "idolmaster";
  if (/Umamusume|Tracen Academy/i.test(t)) return "umamusume";
  return null;
};

// A card's class for deck-identity purposes: its collab class if it is a collab
// card, otherwise its base craft (forest/sword/.../neutral).
export const cardClass = (name) =>
  collabClass(name) || (cardData[name] && cardData[name].class) || "";

// A deck's overall class = its most common non-neutral card class. Most decks
// are mono-class; for a rare multi-class deck the majority wins (e.g. 21 dragon
// + 19 sword -> dragon). Neutral cards don't vote. Returns "" for an empty or
// all-neutral deck. Used as a fallback when a deck has no explicit class set.
export const computeDeckClass = (cards) => {
  const tally = {};
  for (const name of cards || []) {
    const c = cardClass(name);
    if (!c || c === "neutral") continue;
    tally[c] = (tally[c] || 0) + 1;
  }
  let best = "";
  let bestN = 0;
  for (const c in tally) {
    if (tally[c] > bestN) {
      best = c;
      bestN = tally[c];
    }
  }
  return best;
};

// Numeric cost, or null for cards that show "-"/"X"/no cost (leaders, most
// evolved followers, tokens). Used for cost bucketing + the mana curve.
export const getCost = (name) => {
  const d = cardData[name];
  if (!d) return null;
  const n = parseInt(d.cost, 10);
  return Number.isNaN(n) ? null : n;
};

// The site lists composite card types ("Follower / Evolved", "Spell / Token").
// We filter on the primary (first) segment.
export const primaryType = (name) => {
  const d = cardData[name];
  if (!d || !d.cardType) return "";
  return d.cardType.split("/")[0].trim();
};

// Traits are "/"-separated composites ("Arcana / Mage / Cutthroat"). Atomic
// tokens are far more useful for filtering than the 400+ raw combinations.
export const traitTokens = (name) => {
  const d = cardData[name];
  if (!d || !d.trait || d.trait === "-") return [];
  return d.trait.split("/").map((t) => t.trim()).filter(Boolean);
};

// ---- Distinct filter option lists (computed once) ----

export const CARD_TYPES = ["Follower", "Spell", "Amulet", "Leader"];

// Fixed display order; only those actually present are kept.
const RARITY_ORDER = ["Legendary", "Gold", "Silver", "Bronze", "Ultimate", "Special", "Premium"];

export const RARITIES = (() => {
  const present = new Set();
  for (const name in cardData) {
    const r = cardData[name].rarity;
    if (r && r !== "-") present.add(r);
  }
  return RARITY_ORDER.filter((r) => present.has(r));
})();

export const TRAITS = (() => {
  const set = new Set();
  for (const name in cardData) {
    for (const t of (cardData[name].trait || "").split("/")) {
      const v = t.trim();
      if (v && v !== "-") set.add(v);
    }
  }
  return [...set].sort();
})();

export const COST_BUCKETS = ["0", "1", "2", "3", "4", "5", "6", "7", "8+"];
export const STAT_BUCKETS = ["0", "1", "2", "3", "4", "5", "6", "7", "8+"];

const numOrNull = (s) => {
  const n = parseInt(s, 10);
  return Number.isNaN(n) ? null : n;
};
const bucket = (n) => (n == null ? null : n >= 8 ? "8+" : String(n));

// filters: { types, traits, rarities, costs, attacks, defenses } — each an array;
// empty array = no constraint for that category. Categories combine with AND.
export const matchesFilters = (name, filters) => {
  if (!filters) return true;
  const { types = [], traits = [], rarities = [], costs = [], attacks = [], defenses = [] } = filters;
  const d = cardData[name];
  if (types.length) {
    if (!d || !types.includes(primaryType(name))) return false;
  }
  if (rarities.length) {
    if (!d || !rarities.includes(d.rarity)) return false;
  }
  if (costs.length) {
    const b = bucket(getCost(name));
    if (b == null || !costs.includes(b)) return false;
  }
  if (attacks.length) {
    const b = bucket(d ? numOrNull(d.attack) : null);
    if (b == null || !attacks.includes(b)) return false;
  }
  if (defenses.length) {
    const b = bucket(d ? numOrNull(d.defense) : null);
    if (b == null || !defenses.includes(b)) return false;
  }
  if (traits.length) {
    const tokens = traitTokens(name);
    if (!traits.every((t) => tokens.includes(t))) return false;
  }
  return true;
};

export const hasActiveFilters = (filters) =>
  !!filters &&
  ["types", "traits", "rarities", "costs", "attacks", "defenses"].some(
    (k) => filters[k] && filters[k].length
  );
