export const dragonDeck = [
  "Bellringer Angel",
  "Bellringer Angel",
  "Bellringer Angel",
  "Blazing Breath",
  "Blazing Breath",
  "Blazing Breath",
  "Dragon Oracle",
  "Dragon Oracle",
  "Dragon Oracle",
  "Surefire Bullet",
  "Surefire Bullet",
  "Dragon Warrior",
  "Dragon Warrior",
  "Dragon Warrior",
  "Aiela, Dragon Knight",
  "Aiela, Dragon Knight",
  "Serpent's Wrath",
  "Serpent's Wrath",
  "Serpent's Wrath",
  "Path to Purgatory",
  "Path to Purgatory",
  "Execution",
  "Execution",
  "Dark Dragoon Forte",
  "Dark Dragoon Forte",
  "Dark Dragoon Forte",
  "Dark Angel Olivia",
  "Dark Angel Olivia",
  "Dark Angel Olivia",
  "Shenlong",
  "Conflagration",
  "Conflagration",
  "Conflagration",
  "Oguri Cap",
  "Oguri Cap",
  "Riko Kashimoto [Planned Perfection]",
  "Bahamut",
  "Bahamut",
  "Hishi Akebono",
  "Hishi Akebono",
];
